### ISSUE TITLE
Deleting keys from the options hash does not restart the service

### ISSUE THREAD

**Issue by rohte** [deric/puppet-mesos#73]
When one deletes a key from the options hash there is no notify and therefore the service does not get restarted.

**Comment by deric** [comment]
Which version do you use?

**Comment by rohte** [comment]
latest

**Comment by deric** [comment]
Good, service notification was refactored in [v0.7.0](https://github.com/deric/puppet-mesos/releases/tag/v0.7.0) mostly part of #56. AFIK we didn't handle deleted keys before.

I guess the issue is that we're applying [purge](https://github.com/deric/puppet-mesos/blob/master/manifests/master.pp#L99) on the configuration directory. If you delete a key, puppet will remove the corresponding file a nobody gets notified.

**Comment by deric** [comment]
@rohte I wrote a quickfix for the issue, could you test it?

**Comment by rohte** [comment]
Works fine for master and slave at least in our Vagrant set up.
Tested by: 
- Start VM
- Puppet apply
- Check option is there
- Remove some option
- Puppet apply.
- Check option is gone

**Comment by deric** [comment]
Great, I haven't tested whether this works for child directories like: `/etc/mesos-slave/resources`, but with `recurse => true` it should be ok. Reopen if you encounter any issues.

**Comment by deric** [comment]
Fixed in [v0.8.1](https://github.com/deric/puppet-mesos/releases/tag/v0.8.1).
